# Generated by Django 4.2.2 on 2023-06-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='jenis_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paket.jenis'),
        ),
    ]
